name: Crystal Spec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Shards install
      run: shards install
    - name: Run tests
      run: LOG_LEVEL=error crystal spec
